version: 1.0.{build}
branches:
  except:
  - master
  - gh-pages
image: Visual Studio 2015
configuration: Release
environment:
  PAPERTRAIL_SERVER:
    secure: wvCG4LlUnqfPVId8pv089HoZj3ywuIn52/348tuIHE8=
  PAPERTRAIL_PORT:
    secure: BByW+dd9wN7jF4BTkThXsA==
  APPVEYOR_NUGET_NAME:
    secure: z6aDDOkvMnTUmmqk/zsq/BvfFwTyXDG6HqvtcR2WZ/Y=
  APPVEYOR_NUGET_PASSWORD:
    secure: JjPWXO4X/ihcGcVfToq8/A==
  YANDEX_DISK_TOKEN:
    secure: LX6gl4NMLAkkBfVRxj57OTUC2Vj1lJN4UgH6hHQ+icSpf5Saw9Gxt8XNUHmkPXfe
install:
- ps: >-    
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
    choco install -y nxlog --no-progress
    
    $config = (curl 'https://help.papertrailapp.com/assets/files/nxlog.conf.sample') -replace 'logsN.papertrailapp.com',$env:PAPERTRAIL_SERVER -replace 'XXXXX',$env:PAPERTRAIL_PORT -replace 'C:\\\\path\\\\to\\\\\*\.log',(($env:TMP -replace '\\','\\'), "$env:APPVEYOR_REPO_BRANCH.log" -join '\\')
    
    [IO.File]::WriteAllLines("${env:ProgramFiles(x86)}\nxlog\conf\nxlog.conf", $config, (New-Object System.Text.UTF8Encoding $False))
    
    net stop nxlog
    
    net start nxlog
    
    choco source add -n=appveyor -s 'https://ci.appveyor.com/nuget/galeksandrp' -u $env:APPVEYOR_NUGET_NAME -p $env:APPVEYOR_NUGET_PASSWORD
build_script:
- cmd: >-
    cd /d "%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_REPO_BRANCH%"
    
    choco pack
test_script:
- ps: >-
    cd "$env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_REPO_BRANCH"
    
    [xml]$nuspec = cat "$env:APPVEYOR_REPO_BRANCH.nuspec"
    
    choco install -y $env:APPVEYOR_REPO_BRANCH -s '.;https://chocolatey.org/api/v2/;https://www.myget.org/F/galeksandrp/api/v2;https://ci.appveyor.com/nuget/galeksandrp' --version $nuspec.package.metadata.version --pre --no-progress | Out-File -Encoding UTF8 "$env:TMP/$env:APPVEYOR_REPO_BRANCH.log"
    
    if ($env:APPVEYOR_REPO_COMMIT_MESSAGE.Contains('[ci rdp]')) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}
    
    choco uninstall -y $env:APPVEYOR_REPO_BRANCH
