init:
- ps: >-
    choco apikey --key $env:MYGET_API_KEY --source https://www.myget.org/F/galeksandrp/api/v2/package
build_script:
- ps: >-
    if (!$env:APPVEYOR_REPO_COMMIT_MESSAGE.Contains('[ci skiptest]')) {
        git diff --name-only HEAD~ | % {echo $_.split('/')[0]} | sort | Get-Unique | % {
            [xml]$nuspec = cat $_/$_.nuspec
            choco pack $_/$_.nuspec
            choco install $_ -s '.;https://chocolatey.org/api/v2/' --version $nuspec.package.metadata.version --pre
            choco uninstall $_
        }
    }
deploy_script:
- ps: >-
    if ($env:APPVEYOR_REPO_COMMIT_MESSAGE.Contains('[ci push]')) {
        ls *.nupkg | % {choco push --source https://www.myget.org/F/galeksandrp/api/v2/package $_}
    }
